url: https://www.lisannemathijssen.nl
baseurl:

# Site settings
title: Lisanne Mathijssen
email: lisannemathijssen@gmail.com
description: "Lisanne Mathijssen is literair redacteur en schrijver. Ze begeleidt schrijvers bij het maken van hun boek en schreef het boek 'Oorlogsbrieven'."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Lisanne Mathijssen
  pic: 1
  position: Redacteur en schrijver
  social:
    - title: twitter
      url: http://twitter.com/Lytje
    - title: facebook
      url: http://facebook.com/lisannemathijssen
    - title: linkedin
      url: http://linkedin.com/in/lisannemathijssen
    - title: envelope-o
      url: mailto:lisannemathijssen@gmail.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: twitter
      url: http://twitter.com/Lytje
    - title: facebook
      url: http://facebook.com/lisannemathijssen
    - title: linkedin
      url: http://linkedin.com/in/lisannemathijssen
    - title: pencil
      url: http://www.taal-correctie.nl
    - title: envelope-o
      url: mailto:lisannemathijssen@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
